### PR TITLE
ENH: Display patient name, ID, Study and SeriesDescription in title bar

### LINKED ISSUE #31: (Priority 3) Include more info in title bar
Include Patient name, number, study description and series description in the title bar.

### PR DESCRIPTION
**Pull request by jcfr**
Fixes #31

| Before | After |
|--|--|
| image | image |

### CODE REVIEW

**Comment by spycolyf** [comment]
I'm not seeing the demographics in the title bar. Here's what I see...

SlicerTitleBarMissingDemographics

Also, if the title format could be more like the following where there is space (visual separation) that would be great. 

QREADSTitleBar

Remove the version number, and make it more like QREADS title bar...

Example:  Insert the suggested icon (see below) followed by "Patient Number: ######       Patient Name: John Doe        Study Description: CT Torso       Series Description: Lung Scan"
      
Suggestion for an icon:

SlicerQREADSIcon_Color64

Use the following Icon in the place of the Slicer window level icon...

WindowLevel

WindowLevelIcon

**Comment by jcfr** [comment]
> I'm not seeing the demographics in the title bar. Here's what I see...

Make sure to re-run the target as explained in the email.

Code is the following:

https://github.com/KitwareMedical/SlicerQReads/blob/fff532db17159791fc5917b2ca72b92f44312a1d/Modules/Scripted/QReads/QReads.py#L224-L235

> re: icon 

Thanks, will update when back at the computer tomorrow morning.


> Remove the version number, and make it more like QREADS title bar...

How does that look:

```diff
-SlicerQReads X.Y.Z YYYY-MM-DD {PatientName} - {PatientID} - {StudyDescription} - {SeriesDescription}
+SlicerQReads\t Patient Number: {PatientID}\t Patient Name: {PatientName}\t Study Description:{StudyDescription}\t Series Description: {SeriesDescription}
```

**Comment by spycolyf** [comment]
Here is a Mock up of the title bar and the here is the title bar icon.

SlicerTitleBarMissingDemographics

SlicerQREADSIconNew_Color64

**Comment by spycolyf** [comment]
I included a title bar mock up and a new icon here:  https://github.com/KitwareMedical/SlicerQReads/pull/56

This is most QREADS-Like which is what management likes.

Thanks

**Comment by spycolyf** [comment]
Looks good: Remove the SlicerQREADS name and include only the icon and the Patient info as seen in the Picture above. This one is the MPR icon and when we do the Fusion one, a Fusion icon will be used. To have SlicerQREADS on both will be confusing.

**Pull request merged**
