### PR TITLE
WIP: Add support for toggling orientation marker, updating visbility of static ruler

### PR DESCRIPTION
**Pull request by jcfr**
This pull request implements the remaining changes there were associated with `DougMayoSlicerQREADSBranch`

### CODE REVIEW

**Review by spycolyf — APPROVED** [review]

**Comment by jcfr** [comment]
@spycolyf  This is not ready for integration, could you provide two icons ?

**Comment by spycolyf** [comment]
Yes, this is the one I had not finished. The Idea is that the icons change depending in the mode. The Orientation marker toggle  is meant to be a 3 way toggle whose icon changes from axes to human to no marker. The ruler is just a regular toggle with a yellow ruler icon. This can be done later in another version. I will finish this later. I think we're ready to merge and build the other changes. This one will have to wait for a later version if necessary. It can be placed in the backlog.

**Comment by jcfr** [comment]
> I think we're ready to merge and build the other changes

All other changes have been integrated.

Could you more specific?

**Comment by spycolyf** [comment]
Yes, don’t worry about the orientation Marker and ruler toggles. I’ll do those later if necessary. You’ve closed many issues. Are they all merges and ready for me to get and build on my system?

**Comment by spycolyf** [comment]
Ok, thanks JC. I will get the latest and build.

**Comment by jcfr** [comment]
> Are they all merges and ready for me to get and build on my system?

Indeed, yesterday I sent you an email with all the details along with action items for you.

**Comment by spycolyf** [comment]
OK, sorry. Still getting used to GitHub.

**Comment by jcfr** [comment]
> The Orientation marker toggle is meant to be a 3 way toggle whose icon changes from axes to human to no marker. The ruler is just a regular toggle with a yellow ruler icon. This can be done later in another version


If you provide me with icons to use in the toolbar, I could finalize and integrate.

**Comment by spycolyf** [comment]
@jcfr 

Here are the Icons. Thanks.

[OrientationMarkerAndRulerIcons.zip](https://github.com/KitwareMedical/SlicerQReads/files/6368002/OrientationMarkerAndRulerIcons.zip)

**Comment by jcfr** [comment]
Closing. This pull request has been superseded bu #89 and #91

**Pull request closed without merging**
