### PR TITLE
Swapped CT-Lung and CT-Body W/L preset values

### LINKED ISSUE #66: Lung and Body W/L presets are reversed.
We need to reverse the preset values.

### PR DESCRIPTION
**Pull request by spycolyf**
Signed-off-by: Doug Porter <porter.douglas@mayo.edu>

### CODE REVIEW

**Comment by jcfr** [comment]
## Request review

You can ask someone to review by assigning a reviewer:

image


## Commit title

We suggest to use imperative mood when writing commit title.

Instead of `Swapped CT-Lung and CT-Body W/L preset values`, I suggest:

```
BUG: Swap CT-Lung and CT-Body W/L preset values

This commit updates the preset values that were incorrectly mapped when initially addressing
issue https://github.com/KitwareMedical/SlicerQReads/issues/14

For reference, typical window level values are documented here: https://radiopaedia.org/articles/windowing-ct

Fixes #66 
```

## Closing issues

An  issue should be closed only after the corresponding code has been effectively integrated in the project. 

For this reason, I re-open the issue https://github.com/KitwareMedical/SlicerQReads/issues/66 and also linked it with the PR:

image

## Referencing issues

I suggest you also reference issue being closed in the commit message.

For example, see https://github.com/KitwareMedical/SlicerQReads/commit/e1cee6c933a95fa7329ba33ef168ebc6fe7a46a2


## Email associated with your profile

The commit you created is associated with a different email.

Could you also associated your email `porter.douglas@mayo.edu` with your GitHub profile? 

See https://github.com/settings/emails
  *

**Review by jcfr — CHANGES_REQUESTED** [review]
See https://github.com/KitwareMedical/SlicerQReads/pull/67#issuecomment-820574445

**Comment by spycolyf** [comment]
Oh yes, just like TFS. Thx.

**Comment by jcfr** [comment]
I fixed the commit message and updated the author email to be `Doug Porter <dporter@mayo.edu>` instead of `Doug Porter <porter.douglas@mayo.edu>`

**Review by jcfr — APPROVED** [review]

**Pull request merged**
